namespace FPVSim.EditorTools
{
    /// <summary>Where the editor tools put generated and default assets.</summary>
    internal static class EditorPaths
    {
        public const string Root = "Assets/FPVSim";

        /// <summary>Default settings assets. Created once, never overwritten by the builder.</summary>
        public const string Settings = Root + "/Settings";
        public const string DroneTuning = Settings + "/DroneTuning.asset";
        public const string PilotSettings = Settings + "/PilotSettings.asset";

        public const string Rendering = Settings + "/Rendering";
        public const string UrpAsset = Rendering + "/FPVSim_URP.asset";
        public const string UrpRenderer = Rendering + "/FPVSim_URP_Renderer.asset";
        public const string VolumeProfile = Rendering + "/FPVSim_PostProcess.asset";

        /// <summary>Everything below here is regenerated by "FPV Sim > Build Test Scene".</summary>
        public const string Generated = Root + "/Generated";
        public const string Materials = Generated + "/Materials";
        public const string Meshes = Generated + "/Meshes";
        public const string Textures = Generated + "/Textures";
        public const string Prefabs = Generated + "/Prefabs";
        public const string Scenes = Generated + "/Scenes";

        public const string DronePrefab = Prefabs + "/FPV_Quad.prefab";
        public const string TestScene = Scenes + "/FPVTestScene.unity";

        /// <summary>URP's default post-processing data shipped inside the package.</summary>
        public const string UrpDefaultPostProcessData =
            "Packages/com.unity.render-pipelines.universal/Runtime/Data/PostProcessData.asset";
    }
}
